name: Publish to PowerShell Gallery

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Restore dependencies
        shell: pwsh
        run: ./build.ps1 -ResolveDependency -Tasks noop

      - name: Build module
        shell: pwsh
        run: ./build.ps1 -Tasks build

      - name: Configure Git for Wiki Publish
        shell: pwsh
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global url."https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/".insteadOf "https://github.com/"


      - name: Publish
        shell: pwsh
        run: ./build.ps1 -Tasks publish
        env:
          GitHubToken: ${{ secrets.GITHUB_TOKEN }}
          GalleryApiToken: ${{ secrets.POWERSHELL_GALLERY_API_KEY }}
          ReleaseBranch: main
          MainGitBranch: main
          WikiGitUrl: https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.wiki.git
